### PR TITLE
Apply corrections to README

### PR DESCRIPTION
**Pull request by ashmaroli**
Made some corrections to the repo's README based on my initial trials with the plugin. Let me know if you need any changes to be made..

### CODE REVIEW

**Comment by ashmaroli** [comment]
Hello @pixelastic I would also like to point out that its considered a good practice in Ruby to relax version constraints to the closest `MINOR_VERSION`, unless serious bug has been fixed in a certain `PATCH` release.
i.e. I request you to consider having the documentation changed to:
```diff
- The plugin requires a minimum version of Jekyll of 3.6.2 and a Ruby version of 2.3.5.
+ The plugin requires a minimum version of Jekyll of 3.6.x and a Ruby version of 2.3.x.
```
Also, to actually enforce the above constraints, the check has to made in the `gemspec` as well..

**Comment by pixelastic** [comment]
Hello @ashmaroli  and thanks a lot for this great PR.

I especially liked that you documented the three ENV variables used. I would just add that I don't think setting the application_id and index_name in the `_config.yml` is unsecure. I would even say it's the best practice as it's very convenient and both those information will be publicly available from your front-end code anyway, so they should be considered as public data. The only private information is the api key that you definitely don't want to end up publicly available on GitHub if you commit your `_algolia_api_key` file by mistake.

If you think you could reword this part, I'll gladly accept the PR right away, otherwise I'll reword this myself.

As for the constraints on the `MINOR_VERSION` that's a fair point. Do you think it should be made both on the Ruby version and the Jekyll version? Because the plugin is monkey-patching an internal Jekyll method, changes even in minor Jekyll version can have an impact on the plugin. Making sure tests pass for several Jekyll version will require a bit more tooling on my side, but it's doable.

Lastly, I don't have much experience in enforcing those constraints in the `gemspec`. Any PR or pointers here would be much appreciated.

Thanks for the contribution,

**Comment by ashmaroli** [comment]
> both those information will be publicly available from your front-end code anyway

I was not aware of this little bit.. I'll make the update shortly.

> Because the plugin is monkey-patching an internal Jekyll method, changes even in minor Jekyll version can have an impact on the plugin

I've submitted another PR that replaces the monkey-patching using inheritance. With that, you should be covered until Jekyll decides to remove `#write` method from within `Site#process`. Therefore, IMO, you can support even much older Jekyll versions because I honestly do not see the use of any "feature" or "new-code" introduced in Jekyll 3.6

Regarding Ruby versions, I'm in favor of the lock to at least `2.3.0` as 2.2 is slated for EOL in 4months..
I'll submit a PR regarding that as well.

**Comment by pixelastic** [comment]
Thanks for the contribution. I'm going to look at your other PRs.

**Pull request merged**
